{
 "title": "TestOps",
 "tags": [
  "testops",
  "allure-testops",
  "allure"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(process_uptime_seconds,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_count{instance=~\"$instance\"}",
     "legendFormat": "CPU Count"
    },
    {
     "expr": "system_cpu_usage{instance=~\"$instance\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{instance=~\"$instance\"}",
     "legendFormat": "Load Average [1m]"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "disk_total_bytes{instance=\"$instance\"}",
     "legendFormat": "total- {{path}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "expr": "disk_total_bytes{instance=\"$instance\"} - disk_free_bytes{instance=\"$instance\"}",
     "legendFormat": "used - {{path}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "expr": "disk_free_bytes{instance=\"$instance\"}",
     "legendFormat": "free - {{path}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Event levels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=~\"$instance\"}[1m]) > 0",
     "legendFormat": "{{level}}"
    }
   ]
  },
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Incoming RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{instance=~\"$instance\",  uri!~\"/management/.*\", uri!~\"/.well-known/.*\"}[5m]))",
     "legendFormat": "Traffic"
    }
   ]
  },
  {
   "title": "Average HTTP Request Processing Time",
   "type": "timeseries",
   "description": "This chart shows the average processing time of HTTP requests over the last 5 minutes. It helps monitor server performance and detect any delays in request handling.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{instance=~\"$instance\", uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{ instance=~\"$instance\", uri!~\".*actuator.*||.*/management/.*\"}[5m])",
     "legendFormat": "[{{status}}] {{method}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{instance=~\"$instance\", uri!~\".*actuator.*||.*/management/.*\"}[5m]) > 0.1",
     "legendFormat": "[{{status}}] {{method}} - {{uri}}"
    }
   ]
  },
  { "title": "RabbitMQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_connections{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average message processing",
   "type": "timeseries",
   "description": "Average message processing time for RabbitMQ listeners per minute.\nThis metric is useful for analyzing the performance of RabbitMQ listeners. For example, if the average message processing time increases, it may indicate an issue with message handling or an increase in message complexity.",
   "gridPos": { "h": 8, "w": 22, "x": 2, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(spring_rabbitmq_listener_seconds_sum{instance=~\"$instance\"}[1m]) / rate(spring_rabbitmq_listener_seconds_count{instance=~\"$instance\"}[1m])\r\n",
     "legendFormat": "{{queue}} - {{result}}"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_channels{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Published vs Consumed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "irate(rabbitmq_published_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "published"
    },
    {
     "expr": "irate(rabbitmq_consumed_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "consumed"
    }
   ]
  },
  {
   "title": "Acknowledged vs Not acknowledged",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "irate(rabbitmq_acknowledged_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "acknowledged"
    },
    {
     "expr": "irate(rabbitmq_not_acknowledged_published_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "not_acknowledged"
    }
   ]
  },
  {
   "title": "Message Delivery Issues",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "irate(rabbitmq_failed_to_publish_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "failed_to_publish"
    },
    {
     "expr": "irate(rabbitmq_unrouted_published_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "unrouted"
    },
    {
     "expr": "irate(rabbitmq_rejected_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "rejected"
    }
   ]
  },
  {
   "title": "Max Execution Time of RabbitMQ Message Listeners",
   "type": "timeseries",
   "description": "Visualize the maximum execution time of RabbitMQ message listener methods in Spring Framework. This graph provides insights into the longest duration taken for processing messages, aiding in the identification of potential performance bottlenecks. Monitoring this metric supports the optimization of message listener methods for efficient message processing.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(spring_rabbitmq_listener_seconds_max{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "JDBC Connections",
   "type": "stat",
   "gridPos": { "h": 16, "w": 3, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections{instance=~\"$instance\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Connections Active",
   "type": "timeseries",
   "description": "Represents the number of active connections currently in use.\nMonitoring the number of active connections helps in understanding the load on the database and identifying if the pool is under-provisioned.",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 70 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{instance=~\"$instance\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Connections Idle",
   "type": "timeseries",
   "description": "Number of idle connections in the pool.\nHelps in understanding the pool's capacity and its ability to handle sudden spikes in demand.",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 70 },
   "targets": [
    {
     "expr": "hikaricp_connections_idle{instance=~\"$instance\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Connections Timeout",
   "type": "timeseries",
   "description": "Total number of connection timeout occurrences.\nUseful for identifying issues where connections cannot be acquired within the configured timeout, indicating potential performance problems.",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 78 },
   "targets": [
    {
     "expr": "irate(hikaricp_connections_timeout_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Connections Pending",
   "type": "timeseries",
   "description": "Number of connection requests that are currently pending.\nIndicates if there is a backlog in connection requests, which can suggest the pool is under heavy load or not adequately sized.",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 78 },
   "targets": [
    {
     "expr": "hikaricp_connections_pending{instance=~\"$instance\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  }
 ]
}