global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'external-metrics'
    metrics_path: /api/management/prometheus
    scheme: https
    static_configs:
      - targets: ['sandbox.testops.cloud']

  - job_name: 'testops'
    metrics_path: /api/management/prometheus
    dns_sd_configs:
      - names:
          - 'testops'
        type: 'A'
        port: 8080

  - job_name: 'testops-rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'testops-postgresql'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'testops-minio'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio-local:9000']

